# Generated by Django 3.1.5 on 2021-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210314_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='avatar',
            field=models.CharField(default='avatar01.svg', max_length=12),
            preserve_default=False,
        ),
    ]
