# Generated by Django 3.1.5 on 2021-03-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210315_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
